name: Selenium workflow

jobs:
  Selenium-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'adopt'

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-ubuntu
          restore-keys: |
            ${{ runner.os }}-maven-ubuntu

      - name: Install dependencies
        run: |
          mvn install -DskipTests

      - name: Run tests
        run: |
          mvn --batch-mode test "-DsuiteFile=${{ inputs.test_config }}"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Reports - ${{ inputs.test_name }}
          path: |
            CheckoutFolder/target/BufferLog.
            CheckoutFolder/target/ExtentReport.html
            CheckoutFolder/recording_video

      - name: Remove cloned repo
        if: ${{ inputs.artifact != '' }}
        run: |
          rm -r CheckoutFolder